services:
  - type: web
    name: ml-rainfall-forecast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.headless true --server.enableCORS false --server.enableXsrfProtection false --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
